# Generated by Django 4.0.2 on 2022-05-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_reg_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
