# Generated by Django 4.0.2 on 2022-05-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plant_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('flowering_date', models.DateField(max_length=200)),
                ('fruiting_date', models.DateField(max_length=200)),
                ('fertilization_date', models.DateField(max_length=200)),
                ('harvesting_date', models.DateField(max_length=200)),
                ('harvested_data', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.DeleteModel(
            name='plant_details',
        ),
    ]
