# Generated by Django 4.0.2 on 2022-05-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_plantdetails_delete_plant_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='soil_sample_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='periodic_tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('measurement', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='man_power_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
                ('number_of_peoples', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=200)),
                ('applied_quantity', models.CharField(max_length=200)),
                ('applied_date', models.DateField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='farm_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('morning', models.CharField(max_length=200)),
                ('evening', models.CharField(max_length=200)),
                ('average', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='farm_revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_inputs', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('selling_price', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='farm_machineries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=200)),
                ('number_of_machines', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='farm_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
    ]
