# Generated by Django 4.0.2 on 2022-05-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_soil_sample_test_periodic_tests_man_power_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='flowering_date',
            field=models.CharField(max_length=200),
        ),
    ]
