# Generated by Django 4.0.2 on 2022-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_plantdetails_flowering_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='fertilization_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='fruiting_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='harvesting_date',
            field=models.CharField(max_length=200),
        ),
    ]
