# Generated by Django 4.0.2 on 2022-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_plantdetails_fertilization_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='fertilization_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='flowering_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='fruiting_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='harvesting_date',
            field=models.DateField(max_length=200),
        ),
    ]
