# Generated by Django 4.0.2 on 2022-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_machineries',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_machineries',
            name='machine_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_machineries',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_applications',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='man_power_usage',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='man_power_usage',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='periodic_tests',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soil_sample_test',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
