# Generated by Django 4.0.2 on 2022-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_farm_machineries_date_farm_machineries_machine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_expenses',
            name='expenditure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_expenses',
            name='expense',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_expenses',
            name='total_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_expenses',
            name='type_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
