# Generated by Django 4.0.2 on 2022-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_farm_expenses_expenditure_farm_expenses_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_revenue',
            name='revenue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_revenue',
            name='revenue_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_revenue',
            name='type_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
