# Generated by Django 4.0.2 on 2022-07-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_chart_a_alter_chart_b_alter_chart_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_revenue',
            name='farm_inputs',
        ),
        migrations.RemoveField(
            model_name='farm_revenue',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='farm_revenue',
            name='total',
        ),
    ]
