# Generated by Django 4.0.2 on 2022-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_farm_revenue_farm_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_revenue',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
