# Generated by Django 4.0.2 on 2022-07-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
