# Generated by Django 4.0.2 on 2022-07-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chart',
        ),
    ]
