# Generated by Django 4.0.2 on 2022-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_expenses',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm_revenue',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
