# Generated by Django 4.0.2 on 2022-07-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_farm_expenses_date_farm_revenue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetails',
            name='pest_control_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='planting_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
