# Generated by Django 4.0.2 on 2022-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_plantdetails_pest_control_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_applications',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
