# Generated by Django 4.0.2 on 2022-07-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_fertilizer_applications_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='fertilization_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='harvesting_date',
            field=models.CharField(max_length=200),
        ),
    ]
