# Generated by Django 4.0.2 on 2022-08-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_plantdetails_fertilization_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetails',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
