# Generated by Django 4.0.2 on 2022-08-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_plantdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_applications',
            name='plant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
