# Generated by Django 4.0.2 on 2022-08-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_fertilizer_applications_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='man_power_usage',
            name='total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
