# Generated by Django 4.0.2 on 2022-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_man_power_usage_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_machineries',
            name='total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
