# Generated by Django 4.0.2 on 2022-08-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_farm_machineries_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetails',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
