# Generated by Django 4.0.2 on 2022-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_plantdetails_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cpassword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
