# Generated by Django 4.0.2 on 2022-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_register_cpassword_register_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='fertilization_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='flowering_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='fruiting_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='harvested_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='harvesting_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
