# Generated by Django 4.0.2 on 2022-08-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_plantdetails_fertilization_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='flowering_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='fruiting_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetails',
            name='pest_control_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
