# Generated by Django 4.0.2 on 2022-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_plantdetails_flowering_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
