# Generated by Django 4.0.2 on 2022-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_fertilizer_applications_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil_sample_test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
