# Generated by Django 4.0.2 on 2022-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_soil_sample_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_weather',
            name='noon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
