# Generated by Django 4.0.2 on 2022-09-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='acres',
            new_name='acers',
        ),
    ]
