# Generated by Django 4.0.2 on 2022-10-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_acres_location_acers'),
    ]

    operations = [
        migrations.AddField(
            model_name='man_power_usage',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
