# Generated by Django 4.0.2 on 2022-10-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_man_power_usage_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_machineries',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
