# Generated by Django 4.0.2 on 2022-10-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_farm_machineries_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soil_sample_test',
            old_name='file',
            new_name='photo',
        ),
    ]
