# Generated by Django 4.0.2 on 2022-10-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_file_soil_sample_test_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_sample_test',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soil_sample_test',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soil_sample_test',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soil_sample_test',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soil_sample_test',
            name='tests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soil_sample_test',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
