# Generated by Django 4.0.2 on 2022-10-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='graph',
        ),
    ]
