# Generated by Django 4.0.2 on 2022-10-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='harvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('harvesting_date', models.CharField(blank=True, max_length=200, null=True)),
                ('harvested_data', models.CharField(blank=True, max_length=200, null=True)),
                ('planting_date', models.DateField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register')),
            ],
        ),
    ]
