# Generated by Django 4.0.2 on 2022-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_harvesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvesting',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='harvesting',
            name='total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='harvesting',
            name='harvesting_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
