# Generated by Django 4.0.2 on 2022-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_harvesting_cost_harvesting_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
